### ISSUE TITLE
Feature Request - Duplicates

### ISSUE THREAD

**Issue by MinesofMoriaCrypto** [ageorge95/LEAF-chia-plot-check-organiser#1]
Ability to detect duplicates, then choose one to delete from GUI.

**Comment by ageorge95** [comment]
Hi,

A new version was released which no longer required any input from the user. This issue/ feature request was implemented in there: https://github.com/ageorge95/LEAF-chia-plot-check-organiser/releases/tag/v1.0

**Comment by MinesofMoriaCrypto** [comment]
Awesome, thanks. :)
