### ISSUE TITLE
Feature Request - config.json with template

### ISSUE THREAD

**Issue by MinesofMoriaCrypto** [ageorge95/LEAF-chia-plot-check-organiser#3]
The config.json loads blank, leaving the user to not know how to configure it.

A better solution would be auto-detecting coin daemons at least for default dirs.

**Comment by ageorge95** [comment]
Hi,
That is a nice idea !

But I do not understand - what does "default dirs for daemons" mean ? Is it somewhere in Program Files ?

Please provide an example (on windows I am building from source and put the built thing in a custom folder, so I do not know what is the default).

**Comment by MinesofMoriaCrypto** [comment]
Windows Binaries install general config and db data including config.yaml to C:\users\USERNAME\.NAMEOFCHAIN\ and install gui client and cli client to C:\users\USERNAME\appdata\local\.NAMEOFCHAIN\

Config.yaml path for user Mines: C:\Users\Mines\.chia\mainnet\config\
GUI chia.exe Path:  C:\Users\Mines\AppData\Local\chia-blockchain\
CLI chia.exe et al Path: C:\Users\Mines\AppData\Local\chia-blockchain\app-1.2.11\resources\app.asar.unpacked\daemon\

Annoyingly, the CLI and daemon path changes by version number for each version.
Basically all the forks use the same paths. I can't think of one that doesn't.

So the config.json that Leaf produces for me on start is this single line:

==========================================

{"check_command_template": {}}

==========================================

Looking at your source, I was able to determine what was supposed be in there and how it should be formatted. Ex:

==========================================

{
  "check_command_template": {
    "XCH": "C:\\Users\\Mines\\AppData\\Local\\chia-blockchain\\app-1.2.11\\resources\\app.asar.unpacked\\daemon\\chia.exe plots check -g {plot_filename}"
    }
}

==========================================

**Comment by MinesofMoriaCrypto** [comment]
What most utilities do is simply find the config.yamls of the chains and run from there. An example worth looking at that might have all the data you're looking for is: https://github.com/ForkFarmer/ForkFarmer

He references them all for his Java utility in this file:
https://github.com/ForkFarmer/ForkFarmer/blob/main/resources/forks.json

**Comment by ageorge95** [comment]
Hi,

A new version was released which no longer required any input from the user. This issue/ feature request was implemented in there: https://github.com/ageorge95/LEAF-chia-plot-check-organiser/releases/tag/v1.0
