### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by MinesofMoriaCrypto** [ageorge95/LEAF-chia-plot-check-organiser#4]
For some reason horizontal scrolling isn't functioning for me. I run a portrait resolution on that set of machines.

![Screenshot (33)](https://user-images.githubusercontent.com/85489556/142188714-77bbff52-8dbd-493e-8c8e-58a39f060d30.png)

**Comment by ageorge95** [comment]
The horizontal bar should activate by itself once the text is greater than the width of the console.

As for your use case, yes, the GUI will need to be dragged around to see the full contents 🙂

BUT, everything from the console is also displayed in the runtime_log.log; you can open that with your favorite text editor and it should look nice on your screen (I recommend notepd++).

**Comment by ageorge95** [comment]
Oh and also - I see that you are using the GUI version for all the forks - that must leave your system starving for RAM.
I gave up on using the GUI and I am only using the CLI for all the forks, My RAM usage and CPU usage dropped by a lot.

**Comment by ageorge95** [comment]
One last tip then I'm done :)

To avoid windows restarting itself for "updates" - you can use this tool: https://github.com/ageorge95/pyTools

It will disable the windows update once every 10 minutes or so, to make sure that it stays disabled.

**Comment by MinesofMoriaCrypto** [comment]
I don't actually use all those GUIs, I use ForkFarmer to run the CLI clientsy and run GUIs as needed to sort some things or when I add a new chain. I leave the GUI links pinned to the taskbar though. The only GUI I run consistently is Chia.

**Comment by MinesofMoriaCrypto** [comment]
I have Win 10 Pro installed, so I can turn off forced restarts right in Windows update, if I was running Windows 10 Home, it would be a problem. I let the updates download as they like, but all forced restarts and the like are turned off.

**Comment by ageorge95** [comment]
Hi,

Is the solution above (see the output in runtime_log.log) feasible in your case ?

**Comment by MinesofMoriaCrypto** [comment]
It's ok, but clunky. It also won't display the vertical scroll when I view the Display Plot Checks. At that point, the advantage versus running the command in Powershell is pretty minimal.

**Comment by ageorge95** [comment]
I'm sad that you see it that way.

Nevertheless you have an exotic setup with your monitors and that may cause issues with the scrolling bars. Should not be the case, but I cannot confirm or deny it, as I cannot test that on my setup.
